version: "3"

services:
  consul-server01:
    image: consul:1.10
    container_name: consul-server01
    hostname: consul-server01
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/server01:/etc/consul.d
    ports:
      - "8500:8500"

  consul-server02:
    image: consul:1.10
    container_name: consul-server02
    hostname: consul-server02
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/server02:/etc/consul.d

  consul-server03:
    image: consul:1.10
    container_name: consul-server03
    hostname: consul-server03
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/server03:/etc/consul.d

  consul-client01:
    image: consul:1.10
    container_name: consul-client01
    hostname: consul-client01
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./clients/consul01:/etc/consul.d

  consul-client02:
    image: consul:1.10
    container_name: consul-client02
    hostname: consul-client02
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./clients/consul02:/etc/consul.d
